CREATE TABLE SERIE_SEIS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    NUMERO_INICIAL NUMBER,
    CANTIDAD_TERMINOS NUMBER,
    SERIE_GENERADA VARCHAR2(4000),
    SUMA_TOTAL NUMBER,
    CONSTRAINT PK_SERIE_SEIS PRIMARY KEY(ID)
);

COMMIT;